---
title: "Simulated populations for evaluation of stock-recruit fitting"
author:
  - name: Iago Mosqueira
    affiliation: a
  - name: Elizabeth Brooks
    affiliation: b
address:
  - code: a
    address: Institute of Smoke and Magic, University of Sometown, Sometown, XY, 12345
  - code: b
    address: Department of Neat Tricks, Whereever State University, Someplace, MC, 67890
    lead_author_surname: Mosqueira and Brooks
doi_footer: "https://github.com/ices-eg/MGWG/tree/master/stock-recruitment"
abstract: |
  Your abstract will be typeset here, and used by default a visually distinctive font.
  An abstract should explain to the general reader the major contributions of the article. 
keywords: [SRR stock assessment simulation]
output: pdf_document
fontfamily: libertine
---

```{r pkgs, echo=FALSE, message=FALSE, warning=FALSE}
library(ggplotFL)
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE,
  results="hide", fig.cap=TRUE, cache=FALSE)

```

# Introduction 

# Operating models

```{r data}
load("../out/oms.RData")
load("../out/metrics.RData")
```


## Initial population

## Stock-recruitment realationships

```{r srrs}
ggplot(FLQuants(
  ricker=predict(srms$rim, ssb=FLQuant(seq(1, 2000, length=100))),
  bevholt=predict(srms$bhm, ssb=FLQuant(seq(1, 2000, length=100))),
  geomean=predict(srms$gmm, ssb=FLQuant(seq(1, 2000, length=100))),
  segreg=predict(srms$hsm, ssb=FLQuant(seq(1, 2000, length=100))),
  replacement=FLQuant(seq(1, 2000, length=100))/c(spr0(eql)),),
  aes(year, data, group=qname, colour=qname)) + geom_line() +
  ylab("Recruits (1000s)") + xlab("SSB (t)") +
  scale_x_continuous(expand=c(0,0),
    labels=floor(seq(1, 2000, length=5)),
    breaks=seq(1, 100, length=5)) +
  scale_y_continuous(sec.axis = sec_axis(~ .,
    breaks = c(160, 415, 380, 455, 842),
    label=c("Ricker", "SegReg", "Mean", "BevHolt", "Replace"))) +
  theme(legend.position="none")
```

## Recruitment deviates

## Stock trajectories

## Observation error

# Grid of scenarios

# Simulated populations

```{r loadoms}
load("../out/oms.RData")
```

```{r plotoms1, fig.cap="Population time series (recruitment, SSB, catch and F) for a single operating model (Scenario No. 1, random walk recruitment deviances, Beverton-Holt SRR and *Roller-coaster* F trajectory). Ribbons show the 80% probabilities, red line the median, while coloured lines show five individual realizations."}
plot(oms[[1]], iter=1:5)
```

```{r plotdevs, fig.cap="Population time series for the same SRR and F trajectory and the three recruitment deviances."}
# 3 x PLOT 3 runs: diff srr, diff trajectory, diff deviances
plot(oms[1:3]) +
  scale_fill_discrete(labels=runs[1:3,'devs']) +
  scale_color_discrete(labels=runs[1:3,'devs'])
```

```{r plotsrms, fig.cap="Population time series for the same recruitment deviances and F trajectory and the four SRRs."}
plot(oms[c(1,4,7,10)]) +
  scale_fill_discrete(labels=runs[c(1,4,7,10),'srm']) +
  scale_color_discrete(labels=runs[c(1,4,7,10),'srm'])
```

```{r plottrajs, fig.cap="Population time series for the same SRR and recruitment deviances, and three population trajectories."}
plot(oms[c(1,13,25)]) +
  scale_fill_discrete(labels=runs[c(1,13,25),'traj']) +
  scale_color_discrete(labels=runs[c(1,13,25),'traj'])
```

